/*******************************************************************************
 * Copyright 2018
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 ******************************************************************************/
package org.platform.aws.resources;

/**
 * Generated class
 */
public class AwsResourceDmsEventsubscription {

    /**
     * The type of source for which AWS DMS provides notification events. For example, if you want to be notified of events generated by a database instance, set this parameter to replication-instance. If you don't specify a value, notifications are provided for all source types. For valid values, see the SourceType parameter for the CreateEventSubscription action in the AWS Database Migration Service API Reference. 
     */
    private String SourceType;

    /**
     * Indicates whether to activate the subscription. If you don't specify this property, AWS CloudFormation activates the subscription. 
     */
    private String Enabled;

    /**
     * A list of event categories that you want to subscribe to for a given source type. If you don't specify this property, you are notified about all event categories. For more information, see Using AWS DMS Event Notification in the AWS Database Migration Service User Guide. 
     */
    private String EventCategories;

    /**
     * The Amazon Resource Name (ARN) of an Amazon SNS topic that you want to send event notifications to. 
     */
    private String SnsTopicArn;

    /**
     * A list of identifiers for which AWS DMS provides notification events. 
     */
    private String SourceIds;

    /**
     * The subscription name. 
     */
    private String SubscriptionName;

    /**
     * The tags that you want to attach to the DMS event subscription. 
     */
    private String Tags;

    /**
     * @return the SourceType
     */
    public String getSourceType() {
        return SourceType;
    }

    /**
     * @param SourceType the SourceType to set
     */
    public void setSourceType(String SourceType) {
	this.SourceType = SourceType;
    }

    /**
     * @return the Enabled
     */
    public String getEnabled() {
        return Enabled;
    }

    /**
     * @param Enabled the Enabled to set
     */
    public void setEnabled(String Enabled) {
	this.Enabled = Enabled;
    }

    /**
     * @return the EventCategories
     */
    public String getEventCategories() {
        return EventCategories;
    }

    /**
     * @param EventCategories the EventCategories to set
     */
    public void setEventCategories(String EventCategories) {
	this.EventCategories = EventCategories;
    }

    /**
     * @return the SnsTopicArn
     */
    public String getSnsTopicArn() {
        return SnsTopicArn;
    }

    /**
     * @param SnsTopicArn the SnsTopicArn to set
     */
    public void setSnsTopicArn(String SnsTopicArn) {
	this.SnsTopicArn = SnsTopicArn;
    }

    /**
     * @return the SourceIds
     */
    public String getSourceIds() {
        return SourceIds;
    }

    /**
     * @param SourceIds the SourceIds to set
     */
    public void setSourceIds(String SourceIds) {
	this.SourceIds = SourceIds;
    }

    /**
     * @return the SubscriptionName
     */
    public String getSubscriptionName() {
        return SubscriptionName;
    }

    /**
     * @param SubscriptionName the SubscriptionName to set
     */
    public void setSubscriptionName(String SubscriptionName) {
	this.SubscriptionName = SubscriptionName;
    }

    /**
     * @return the Tags
     */
    public String getTags() {
        return Tags;
    }

    /**
     * @param Tags the Tags to set
     */
    public void setTags(String Tags) {
	this.Tags = Tags;
    }


}